### ISSUE TITLE
sprite has no property .png error

### ISSUE THREAD

**Issue by Viktorminator** [alexfedoseev/js-app-starter#2]
After initial install and command `npm start` this issue appears:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v0.12.0/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v0.12.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart js-app-starter@0.0.1
6 info start js-app-starter@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info js-app-starter@0.0.1 Failed to exec start script
9 verbose stack Error: js-app-starter@0.0.1 start: `NODE_ENV=development http-server -a lvh.me -p 3500 & gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid js-app-starter@0.0.1
11 verbose cwd /home/user/Repos/js-app-starter
12 error Linux 4.2.0-35-generic
13 error argv "/home/user/.nvm/versions/node/v0.12.0/bin/node" "/home/user/.nvm/versions/node/v0.12.0/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error js-app-starter@0.0.1 start: `NODE_ENV=development http-server -a lvh.me -p 3500 & gulp`
17 error Exit status 1
18 error Failed at the js-app-starter@0.0.1 start script 'NODE_ENV=development http-server -a lvh.me -p 3500 & gulp'.
18 error This is most likely a problem with the js-app-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=development http-server -a lvh.me -p 3500 & gulp
18 error You can get their info via:
18 error     npm owner ls js-app-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by masquel** [comment]
@Viktorminator 
Just add `leave-strings: true` to options
Link: https://github.com/twolfson/gulp.spritesmith/issues/61
